### ISSUE TITLE
can't install the gem

### ISSUE THREAD

**Issue by busterbenson** [mwunsch/tumblr#1]
I'm running Rails 2.3.5 and tried installing your gem and adding config.gem 'tumblr-rb' to environment.rb.  Despite the gem being in my path, I get this error:

no such file to load -- tumblr-rb
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require' 

Am I doing something wrong here?

**Comment by mwunsch** [comment]
the gem is called 'tumblr-rb', but the lib is called 'tumblr', so try this:

`config.gem "tumblr-rb", :lib => "tumblr"`
