### ISSUE TITLE
Add dependency on "main"

### ISSUE THREAD

**Issue by qerub** [mwunsch/tumblr#11]
The application depends on the library "main" but that dependency isn't listed in the gem specification. Please add that so that "gem install tumblr" installs all dependencies.

**Comment by mwunsch** [comment]
It does? I did not realize -- maybe that's a dependency of the "highline" lib? I'll be updating tumblr-rb to use the newest version of bundler, that should be able to capture all dependencies...

**Comment by qerub** [comment]
Oops… No, it doesn't &mdash; I filed this ticket on the wrong project. The problem is with the "tumblr" gem (and not your "tumblr-rb" gem); I guess I was confused by your repository name. Sorry!
