### ISSUE TITLE
Publish To A Specified Blog

### ISSUE THREAD

**Issue by conatus** [mwunsch/tumblr#17]
If one has more than one blog, there is no way of posting to the other blog from the command line. It would be great if this were possible.

Thanks a lot!

**Comment by mwunsch** [comment]
Have you tried the `--group` flag? Is that not what you want?

**Comment by conatus** [comment]
Hullo, 

Thanks very much for the reply.

What is the format of this tag? I tried just the name of the Tumbl-blog and it dumped me out saying not found.

**Comment by mwunsch** [comment]
From the [old api docs](http://www.tumblr.com/docs/en/api/v1):

> group (optional) - Post this to a secondary blog on your account, e.g. mygroup.tumblr.com (for public groups only)

**Comment by conatus** [comment]
Wonderful - shall I amend the documentation for clarity and send a pull?
