### ISSUE TITLE
Blockquote Markdown bug in caption and description

### ISSUE THREAD

**Issue by mottram** [mwunsch/tumblr#2]
Tiny bug: when writing a caption for photo posts, and a description for link posts, the Tumblr gem strips out a leading `>`, making it impossible to use Markdown blockquotes.

Eg:

<pre>

---
type: link
format: markdown
description: > A quote from the _linked_ page, [including another link](http://example.com)

---
http://example.com
</pre>

Will end up on Tumblr without the `>`, but with the rest of the markdown processed fine. (Double blockquotes - `>>` - work, though.)

**Comment by mwunsch** [comment]
This isn't so much a bug with Tumblr as it is an error in YAML's interpretation of your string. Remember that Tumblr just uses YAML frontmatter, which means it just runs this block through a YAML parser.

So YAML is handling the description string in an odd way here. What I suggest, is read up on how YAML does strings (Scalars):

```
description: A quote from the linked page
```

Is really just short for 

```
"description": "A quote from the linked page"
```

You can get around this issue by putting the description in quotes:

```
"> A quote from the _linked_page..."
```

If you look at the YAML spec, at it's handling of [scalars](http://www.yaml.org/spec/1.2/spec.html#id2760844), you'll see that the character `>` has special significance. Quote or use the `|` character to escape the sequence.

**Comment by mottram** [comment]
Ah, apologies for assuming it was the Tumblr gem's fault.
