### ISSUE TITLE
Tumblr says, "Authentication failed."

### ISSUE THREAD

**Issue by labe-me** [mwunsch/tumblr#20]
Hello,

Is it me or has tumblr changed its auth protocol since the 3rd july -date of my last successful usage of tumblr-rb-?

I always get the odious :

Oh no! Something went wrong. Tumblr says, "Authentication failed."

I tried with a fresh github version of tumblr-rb and with different command line parameters without success…

I don't think I changed anything on tumblr side but who knows… 

Thank you for your help!

Best regards
Laurent

**Comment by mwunsch** [comment]
Yes they have changed it! See: http://developers.tumblr.com/post/28557510444/welcome-to-the-official-tumblr-developers-blog

> Now that v2 has reached stability & maturity, this also means it’s time for us to begin to phase out API v1. We will be phasing out all authenticated requests for API v1, while leaving in place all unauthenticated reads. The current date for the phase out of authenticated reads for v1 will tentatively be September 1st, 2012.

I'm working on the v2 branch of tumblr-rb to access the v2 API. It's been slow going but I intend to have a solid 2.0 release out by the end of the month.

**Comment by labe-me** [comment]
Thank you :)
