### ISSUE TITLE
Missing documentation for programmatic usage (no longer supported)? 

### ISSUE THREAD

**Issue by bhaberer** [mwunsch/tumblr#22]
I am using this gem in an IRC Bot that captures links and posts them to a tumblr, and I used to be able to use the gem (the API v1 version) inline to create a tumblr post with a function that took a string (yaml formatted) and created a post like so:

``` ruby
def tublr_post(doc)
  request = Tumblr.new(config[:tumblr][:username], config[:tumblr][:password]).post(doc)
  request.perform do |response|
    if response.success?
      debug "Success"
    else
      debug "Something went wrong  #{response.code} #{response.message}"
    end
  end
end
```

However, now this obviously doesn't work anymore, I've tried a few things after looking over the code changes (am I missing docs somewhere?) and the tumblr binary, but I'm not having a lot of luck. I got it to work by dumping the post to a file and them using the binary, but obviously I'd rather just use the gem inline without having to bother with that.

Any suggestions? Is this just not something you care to support any longer?

**Comment by mwunsch** [comment]
Yes it is something I continue to support, but I decided to release v2 without great documentation for the lib. Documentation is still sorely needed, as the API has experienced significant changes - particularly b/c v2 of the Tumblr API requires OAuth

Try this:

``` ruby
post = Tumblr::Post.load(doc) # doc is your yaml formatted string
client = Tumblr::Client.new(hostname, oauth_hash) # oauth_hash is a hash with keys :consumer_key, :consumer_secret, :token, :token_secret
request = post.post(client)

request.perform do |response|
    debug "Success" if response.success? # works as before
end
```

There's more than one way to do it, and I need to write documentation to help out these common use cases.

**Comment by bhaberer** [comment]
Ah! I was almost doing the right thing, I just wasn't passing in the oauth hash explicitly when I instantiated the client object. (Which is silly since I saw it in the initializer) 

Thanks for the help, and for updating the gem.
