### ISSUE TITLE
Custom Domain Authentication

### ISSUE THREAD

**Issue by wwwjscom** [mwunsch/tumblr#23]
Hi

Thanks for the gem, but I'm having a bit of an issue.  I'm using a custom domain, and it cannot authenticate the gem.  I turned off my custom domain, instead used xyz.tumblr.com, and that worked fine.  Once I re-enabled the custom domain (post authentication), it errors out:

```
~/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/net/http.rb:762:in `initialize': getaddrinfo: nodename nor 
servname provided, or not known (SocketError)
```

Any suggestions?

Thanks!

**Comment by mwunsch** [comment]
I'm not quite sure what you're attempting.  Can you provide more of the stack trace, and more information about your usage? Code snippet would be fantastic.

This error appears when there is a DNS issue. Can you curl the api url?

**Comment by mwunsch** [comment]
@wwwjscom Are you still seeing this issue? If so, can you answer my question?
