### ISSUE TITLE
Couldn't get a file descriptor referring to the console

### ISSUE THREAD

**Issue by alastairhm** [mwunsch/tumblr#26]
Running on Ubuntu 12.04 get the following when trying to authorize, any tips on solving the issue?

alastair@alastair-H61M-S2PV:~$ tumblr authorize
[2013-01-24 22:09:45] INFO  WEBrick 1.3.1
[2013-01-24 22:09:45] INFO  ruby 1.9.3 (2011-10-30) [i686-linux]
== Sinatra/1.3.3 has taken the stage on 4567 for development with backup from WEBrick
Couldn't get a file descriptor referring to the console
[2013-01-24 22:09:45] INFO  WEBrick::HTTPServer#start: pid=8573 port=4567

**Comment by mwunsch** [comment]
[These lines here](https://github.com/mwunsch/tumblr/blob/master/lib/tumblr/command_line_interface.rb#L166-L168)

``` ruby
Tumblr::Authentication.run!(sinatra_options) do |server|
  `open http://#{options[:bind]}:#{options[:port]}/`
end
```

When the authentication app starts up, it attempts to `open` a URL, which on OSX systems will open the default browser application.

I think a fix for this would be to include [Launchy](http://www.copiousfreetime.org/projects/launchy/) and use it to launch the browser.

In the meantime, just go to _http://localhost:4567_ in your browser to complete the authentication process.

**Comment by alastairhm** [comment]
Thanks, I'll give that a try tonight.
Reading up it seems one option would be to do a "gnome-open" on Ubuntu to launch the default browser from the CLI.

**Comment by alastairhm** [comment]
Thanks that worked :)

**Comment by mwunsch** [comment]
Reopening this so I can make sure we open the browser in a cross-platform way.
