### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by cwiggins** [mwunsch/tumblr#28]
I am using Arch Linux and I have tried multiple ruby versions including 1.9.1, 1.9.3, and 2.0.0-rc1 and I get this error message every time I run `tumblr authorize`

> [2013-02-04 16:14:41] INFO  WEBrick 1.3.1
> [2013-02-04 16:14:41] INFO  ruby 1.9.1 (2011-02-18) [x86_64-linux]
> == Sinatra/1.3.4 has taken the stage on 4567 for development with backup from WEBrick
> /home/curtiss/.rvm/gems/ruby-1.9.1-p431/gems/tumblr-rb-2.0.0/lib/tumblr/command_line_interface.rb:156:in ``': No such file or directory - open http://0.0.0.0:4567/ (Errno::ENOENT)
>         from /home/curtiss/.rvm/gems/ruby-1.9.1-p431/gems/tumblr-rb-2.0.0/lib/tumblr/command_line_interface.rb:156:in`block in authorize'
>         from /home/curtiss/.rvm/gems/ruby-1.9.1-p431/gems/sinatra-1.3.4/lib/sinatra/base.rb:1386:in `block in run!'
>         from /home/curtiss/.rvm/gems/ruby-1.9.1-p431/gems/rack-1.4.4/lib/rack/handler/webrick.rb:12:in`run'
>         from /home/curtiss/.rvm/gems/ruby-1.9.1-p431/gems/sinatra-1.3.4/lib/sinatra/base.rb:1378:in `run!'
>         from /home/curtiss/.rvm/gems/ruby-1.9.1-p431/gems/tumblr-rb-2.0.0/lib/tumblr/command_line_interface.rb:155:in`authorize'
>         from /home/curtiss/.rvm/gems/ruby-1.9.1-p431/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
>         from /home/curtiss/.rvm/gems/ruby-1.9.1-p431/gems/thor-0.16.0/lib/thor/invocation.rb:120:in`invoke_task'
>         from /home/curtiss/.rvm/gems/ruby-1.9.1-p431/gems/thor-0.16.0/lib/thor.rb:275:in `dispatch'
>         from /home/curtiss/.rvm/gems/ruby-1.9.1-p431/gems/thor-0.16.0/lib/thor/base.rb:425:in`start'
>         from /home/curtiss/.rvm/gems/ruby-1.9.1-p431/gems/tumblr-rb-2.0.0/bin/tumblr:5:in `<top (required)>'
>         from /home/curtiss/.rvm/gems/ruby-1.9.1-p431/bin/tumblr:19:in`load'
>         from /home/curtiss/.rvm/gems/ruby-1.9.1-p431/bin/tumblr:19:in `<main>'
>         from /home/curtiss/.rvm/gems/ruby-1.9.1-p431/bin/ruby_noexec_wrapper:14:in`eval'
>         from /home/curtiss/.rvm/gems/ruby-1.9.1-p431/bin/ruby_noexec_wrapper:14:in `<main>'

**Comment by mwunsch** [comment]
Same issue as #26 fixed in #27. Try cloning from master -- I'll release a new version of the gem soon.
