### ISSUE TITLE
Unclear documentation for --host

### ISSUE THREAD

**Issue by rrthomas** [mwunsch/tumblr#30]
--host seems to be optional according to the command-line help, but tumblr(1) says it's needed for posting and fetching posts. Yet a lot of the example tumblr post commands don't include it. It would seem to be sensible to be able to include it in ~/.tumblr, but I can't find out how. Help? If it's necessary all the time, it would be nice to make this clear, at least.

**Comment by mwunsch** [comment]
It _is_ optional, b/c the cli first looks for the ENV variable `$TUMBLRHOST`. You can include that env variable in your ~/.bashrc or ~/.profile, etc.

This should be better documented.

**Comment by kristianfreeman** [comment]
@mwunsch - I can write some documentation for this in the next couple days. Expect a PR!

**Comment by mwunsch** [comment]
Thanks @imkmf

**Comment by mwunsch** [comment]
#31 is a start. Will close this issue but continue to prioritize documentation.
