### ISSUE TITLE
Tumblr returned a 404 Error: Not Found

### ISSUE THREAD

**Issue by giacecco** [mwunsch/tumblr#48]
I've installed tumblr-rb-2.1.1, configured it, successfully posted a few times all ok, but then every time I try I get an ```Tumblr returned a 404 Error: Not Found``` error, with no other explanation. I've tried deleting the old credentials and created new successfully, but I still get that error. Any suggestion? Thanks.

G.

**Comment by mwunsch** [comment]
Would love a bit more information to help. What endpoint are you trying to post to? Can you share some of the payload you're trying to send?

**Comment by giacecco** [comment]
@mwunsch I apologise, I've realised that the "m" was missing from the endpoint's domain name.
