### ISSUE TITLE
Posts are not tweeted by default

### ISSUE THREAD

**Issue by rrthomas** [mwunsch/tumblr#6]
According to the tumblr API docs for "send-to-twitter", this has a default value of "no", but:

If this parameter is unspecified, API-created posts will be sent to Twitter if the "Send my Tumblr posts to Twitter" checkbox in the Customize screen is checked.

Unfortunately, tumblr seems to be sending some value for this even when it's not specified in the YAML header for a post, as my posts from tumblr-rb are not tweeted, while my posts from the tumblr interface are.

**Comment by mwunsch** [comment]
This seems to have been resolved with the recent pull request merge.
